---
- name: Allow net port through firewall
  hosts: production
  become: yes

  tasks:
  - block: #======REDHAT======#
      - name: Allow 80/tcp port
        ansible.posix.firewalld:
          port: 80/tcp
          permanent: true
          state: enabled
          zone: public
        notify: Reload Firewalld  
    
    when: ansible_os_family == "RedHat"

  - block: #=======DEBIAN=======#
      - name: Allow 80/tcp port
        community.general.ufw:
          rule: allow
          port: 80
          proto: tcp
    when: ansible_os_family == "Debian"
##################################
  handlers:
  - name: Reload Firewalld
    service:
      name: firewalld
      state: reloaded
