---
- name: Allow net port through firewall
  hosts: RedHat
  become: yes

  tasks:
#########FIREWALLD################
  - name: Allow 80/tcp port
    ansible.posix.firewalld:
      port: 80/tcp
      permanent: true
      state: enabled
      zone: public
    notify: Reload Firewalld  
############UFW####################  
  - name: Allow 80/tcp port
    community.general.ufw:
      rule: allow
      port: 80
      proto: tcp
    notify: Reload ufw
##################################
  handlers:
  - name: Reload Firewalld
    service:
      name: firewalld
      state: reloaded
  - name: Reload ufw
    service:
      name: ufw
      state: reloaded
