---
- name: Allow net port through firewall
  hosts: zbx_external
  become: yes

  tasks:
  - block: #=======DEBIAN=======#
      - name: Allow 10050/tcp port
        community.general.ufw:
          rule: allow
          port: 10050
          proto: tcp
    when: ansible_os_family == "Debian"
##################################
