---
- name: Copy files
  hosts: RedHat
  become: yes
  
  vars:
    src_folder: /home/vm/ansible/html
    dest_folder: /var/www/  

  tasks:

  - block: #=====REDHAT=====#
      - name: Install httpd
        yum:
          name: httpd
          state: installed

      - name: Start httpd
        service:
          name: httpd
          state: started
          enabled: yes

      - name: Allow http service thorugh firewall
        ansible.posix.firewalld:
          port: 80/tcp
          permanent: true
          state: enabled
        notify: Restart firewalld
    when: ansible_os_family == "RedHat"
  
  - name: Copy folder html
    copy:
      src={{ src_folder }}
      dest={{ dest_folder }}
      mode=0555
  when: ansible_os_family == "RedHat"

  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
  - name: Restart firewalld
    service:
      name: firewalld
      state: reloaded

