---
- name: Deny net port through firewall
  hosts: RedHat
  become: yes

  tasks:
  - name: deny ssh
    ansible.posix.firewalld:
      service: http
      permanent: true
      state: disabled
      zone: public 
  - name: deny 8080/tcp port
    ansible.posix.firewalld:
      port: 8080/tcp
      permanent: true
      state: disabled
      zone: public

  - name: reload rule
    service:
      name: firewalld
      state: reloaded
