---
- name: Include playbook
  hosts: RedHat
  become: yes

  
  vars:
   text: "Hi from me"

  tasks:
  - name: Ping
    ping:

  - name: Create folder
    include: create_folder.yml

  - name: Create file
    include: create_file.yml
