---
- name: Loop, with_items, until, with_fileglob
  hosts: RedHat
  become: yes


  tasks: 
  - name: Say Hello to All
    debug: msg="Hello {{ item }}" 
    loop:
        - "1"
        - "2"
        - "3"

  - name: Loop untill example 
    shell: echo -n Z >> myfile.txt && cat myfile.txt
    register: output
    delay: 2
    retries: 10
    until: output.stdout.find("ZZZZZ") == false

  - name: Print final output
    debug: var=output.stdout
 
 # - name: Install many packaged
  #  yum: name={{ item }} state=installed
  #  loop:
   #     - "python"
    #    - "tree"
     #   - "mysql-client"
