---
- name: Reboot servers
  hosts: RedHat
  become: yes


  tasks:
  - name: Reboot servers
    shell: sleep 3 && reboot now
    async: 1
    poll: 0
  - name: Wait till my server will come up online
    wait_for:
        host: "{{ inventory_hostname }}"
        state: started
        delay: 5
        timeout: 40
    delegate_to: 127.0.0.1
