---
- name: Copy files
  hosts: RedHat
  become: yes
  
  vars:
    src_folder: /home/vm/ansible/html
    dest_folder: /var/www/html

  tasks:
  - name: Create folder html
    ansible.builtin.file: path=/var/www/html state=directory

  - block: #=====REDHAT=====#

      - name: Install httpd
        yum: name=httpd state=installed

      - name: Start httpd
        service: name=httpd state=started enabled=yes

      - name: Allow http service thorugh firewall
        ansible.posix.firewalld:
          port: 80/tcp
          permanent: true
          state: enabled
        notify: Restart firewalld
    when: ansible_os_family == "RedHat"
  
  - name: Generate INDEX.HTML file
    template: src={{src_folder}}/index.html dest={{dest_folder}}/index.html mode=0555
    notify: Restart httpd

  - name: Copy files
    copy: src={{ src_folder }}/{{item}} dest={{ dest_folder }} mode=0555
    loop:
        - "never_give_up.jpg"
        - "vertex.jpg"
    notify: Restart httpd

  handlers:
  - name: Restart httpd
    service:
      name: httpd
      state: restarted
      enabled: yes
  - name: Restart firewalld
    service:
      name: firewalld
      state: reloaded

