---
- block: #=====Debian=====#
    - name: Import GPG key for repository
      shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -

    - name: Check file for reository
      stat:
        path: /etc/apt/sources.list.d/elastic-8.x.list
      register: elk_8 
    - name: Create file for repository
      ansible.builtin.file: 
        path: /etc/apt/sources.list.d/elastic-8.x.list
        state: touch
        mode: '0644'
      when: not elk_8.stat.exists

    - name: Write repository url in file
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/elastic-8.x.list
        line: "deb https://artifacts.elastic.co/packages/8.x/apt stable main"
 
    - name: Update packeges
      shell: apt update
    
    - name: Install filebeate
      apt:
        name: filebeat
        state: present
   
    - name: Check filebeat.yml exist
      stat:
        path: /etc/filebeat/filebeat.yml
      register: filebeat_yml

    - name: Copy filebeat.yml
      template:
        src: filebeat.j2
        dest: /etc/filebeat/filebeat.yml
        owner: root
        group: root
        mode: '0644'
      when: not filebeat_yml.stat.exists
      notify: Restart filebeat
      notify: Enable filebeat

        



  when: ansible_os_family == "Debian"

