---
# handlers file for deploy_apache_web
- name: Restart httpd
  service:
    name: httpd
    state: restarted
    enabled: yes
- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded
