---
- block: #=====Debian=====#
    - name: Allow 10050/tcp port
      ufw:
        rule: allow
        port: 10050
        proto: tcp

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: latest
        update_cache: yes

    - name: Copy Zabbix Agent Config
      template:
        src: DEBIANzabbix_agentd.conf.j2
        dest: /etc/zabbix/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'
    - name: Rename zabbix_agentd_conf.d to zabbix_agentd.d
      shell: mv /etc/zabbix/zabbix_agentd.conf.d /etc/zabbix/zabbix_agentd.d
      notify: Restart zabbix-agent

  when: ansible_os_family == "Debian" 

- block: #=====RedHat=====#
    - name: Allow 10050/tcp port
      ansible.posix.firewalld:
        state: enabled
        port: 10050/tcp
        permanent: true

    - name: Enable Zabbix repository
      command: 'dnf install -y https://repo.zabbix.com/zabbix/5.4/rhel/8/x86_64/zabbix-release-5.4-1.el8.noarch.rpm'

    - name: Install Zabbix Agent
      command: 'dnf install zabbix-agent'

    - name: Copy Zabbix Agent Config
      template:
        src: REDHATzabbix_agentd.conf.j2
        dest: /etc/zabbix_agentd.conf
        owner: root
        group: root
        mode: '0644'
      notify: Restart zabbix-agent
    - name: Hostname
      command: 'hostnamectl'
      register: hostname
    - debug:
        var: hostname.stdout
  when: ansible_os_family == "RedHat" 

