---
- name: Restart Pormetheus
  hosts: prometheus
  become: yes

  tasks:

  - block: #=====Debian=====#
      - name: Restart node_exporter.service
        ansible.builtin.systemd:
          name: node_exporter.service
          state: restarted
      - name: Check the status of the service
        ansible.builtin.systemd:
          name: node_exporter.service
        register: service_status
      - name: Display the service status
        debug:
          var: service_status.status.ActiveState

    when: ansible_os_family == "Debian"

