---
- block: #======DEBIAN======#
    - name: Install dependencies
      apt:
        name:
          - build-essential
          - libssl-dev
          - zlib1g-dev
          - libncurses5-dev
          - libncursesw5-dev
          - libreadline-dev
          - libsqlite3-dev
          - libgdbm-dev
          - libdb5.3-dev
          - libbz2-dev
          - libexpat1-dev
          - liblzma-dev
          - tk-dev
          - libffi-dev
    - name: Download Python 2.7 source
      get_url:
        url: https://www.python.org/ftp/python/2.7.18/Python-2.7.18.tgz
        dest: /tmp/Python-2.7.18.tgz
    - name: Extract Python 2.7 source
      ansible.builtin.unarchive:
        src: /tmp/Python-2.7.18.tgz
        dest: /tmp
        remote_src: yes
    - name: Configure and install Python 2.7
      shell: "cd /tmp/Python-2.7.18 && ./configure && make && make install"

  when: ansible_os_family == "Debian"
